errore::test_display::Error: error occurred with 1: ...
    at tests/test_display.rs:162:9

errore::test_display::Error: there was an empty error: ...
    at tests/test_display.rs:163:9